// examples/vue/src/App.vue
<script setup lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
import IconifyLink from "./components/IconifyLink.vue";
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <i-con icon="logos:vitejs" class="logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <i-con icon="logos:vue" class="logo vue" />
    </a>
    <IconifyLink />
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
a {
  display: inline-block;
}
.logo {
  font-size: 6rem;
  width: 1em;
  height: 1em;
  padding: 1.5rem;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2rem #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2rem #42b883aa);
}
</style>

// examples/svelte/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import viteLogo from '/vite.svg'
  import Counter from './lib/Counter.svelte'
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
    <a href="https://iconify.design/" target="_blank" rel="noreferrer">
      <i-con
        icon="simple-icons:iconify"
        class={`logo spin iconify`}
      ></i-con>
    </a>
  </div>
  <h1>Vite + Svelte</h1>

  <div class="card">
    <Counter />
  </div>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
  .iconify {
    width: 6em;
    vertical-align: top;
  }
</style>
